/* Obslide V29.7.17 - Nexity DG Region BBCA podium, projects / housing switch. */
(function(){'use strict';
const C=window.OBSNexityCore,G=window.OBSNexityGeography;
const DG_GROUPS=[
 {id:'grand-ouest',name:'DG Région Grand Ouest',directions:['normandie','bretagne','atlantique']},
 {id:'multiproduits',name:'DR Multiproduits',directions:['centre','val-de-loire']},
 {id:'nord-est',name:'DG Région Nord Est',directions:['nord','est']},
 {id:'est',name:'DG Région Est',directions:['rhone-bourgogne-auvergne','alpes']},
 {id:'sud-ouest',name:'DG Région Sud Ouest',directions:['aquitaine','pays-basque','midi-pyrenees']},
 {id:'sud',name:'DG Région Sud',directions:['languedoc','grand-marseille','var','alpes-maritimes']},
 {id:'idf',name:'DG Région IDF',directions:['ouest-grande-couronne','est-grande-couronne','petite-couronne','agence-94']}
];
const defaults={title:'NEXITY · PODIUM DES DG RÉGION',subtitle:'Performances BBCA par DG Région',filters:{direction:'all',year:'all',moa:'all',mentions:[]},metric:'projects'};
let bridge=null,measureCtx=null;
const e=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const f=v=>Number(v||0).toLocaleString('fr-FR');
const model=()=>bridge.getModel();
function source(){const m=bridge.getSourceModel();if(m?.sourceMode==='connected'){const ops=bridge.operations(),raw=ops.flatMap(o=>o.rawRows?.length?o.rawRows:[o.raw||o]);return C.fromObjects(raw).rows;}return Array.isArray(m?.rows)?m.rows:[];}
function summary(m=model()){
 const all=C.aggregate(source(),G.catalog,bridge.getSourceModel()?.aliases||{},G).projects;
 const projects=C.filter(all,m.filters||{}),metric=m.metric==='housing'?'housing':'projects';
 const levels=['BBCA Excellence','BBCA Performance','BBCA Standard'];
 const groups=DG_GROUPS.map(g=>{const rows=projects.filter(p=>g.directions.includes(p.directionId));const byLevel={};levels.forEach(level=>{const ps=rows.filter(p=>p.bbcaLevel===level);byLevel[level]={projects:ps.length,housing:ps.reduce((a,p)=>a+(Number(p.housing)||0),0)};});return{...g,rows,totalProjects:rows.length,totalHousing:rows.reduce((a,p)=>a+(Number(p.housing)||0),0),byLevel};});
 const rankings={};levels.forEach(level=>{rankings[level]=groups.map(g=>({...g,value:g.byLevel[level][metric]})).sort((a,b)=>b.value-a.value||b.byLevel[level].projects-a.byLevel[level].projects||b.byLevel[level].housing-a.byLevel[level].housing||a.name.localeCompare(b.name,'fr'));});
 return{all,projects,groups,rankings,metric,hasData:source().length>0};
}
function selection(options,selected){return options.map(o=>`<option value="${e(o.value)}" ${String(o.value)===String(selected)?'selected':''}>${e(o.label)}</option>`).join('');}
function mentionMenu(all,selected){const items=all.map(x=>`<label><input type="checkbox" data-nxp-mention value="${e(x)}" ${selected.includes(x)?'checked':''}> <span>${e(x)}</span></label>`).join('');const label=selected.length?`${selected.length} mention${selected.length>1?'s':''}`:'Toutes les mentions';return `<details class="nx-multifilter"><summary>Mention · ${e(label)}</summary><div class="nx-multi-menu"><div class="nx-multi-actions"><button type="button" data-nxp-mention-action="all">Tout</button><button type="button" data-nxp-mention-action="none">Aucune</button></div>${items||'<em>Aucune mention détectée</em>'}</div></details>`;}
function toolbar(m){const s=summary(m),filters=m.filters||{},sel=(label,key,opts)=>`<label class="nx-filter"><span>${label}</span><select data-nxp-filter="${key}">${selection(opts,filters[key]||'all')}</select></label>`;const mentions=[...new Set(s.all.flatMap(p=>p.mentions))].sort((a,b)=>a.localeCompare(b,'fr')),selected=Array.isArray(filters.mentions)?filters.mentions:[];return `<div class="nx-filterbar"><div class="nx-total"><strong>${s.hasData?f(s.projects.length):'—'}</strong><span>projets</span></div>${sel('Direction régionale','direction',[{value:'all',label:'Toutes les directions'},...G.catalog.map(d=>({value:d.id,label:d.name})),{value:'__unassigned__',label:'À vérifier / non rattachés'}])}${mentionMenu(mentions,selected)}${sel('Année','year',[{value:'all',label:'Toutes'},...[...new Set(s.all.flatMap(p=>p.years))].sort().map(x=>({value:x,label:x}))])}${sel('Maître d’ouvrage','moa',[{value:'all',label:'Tous'},...[...new Set(s.all.flatMap(p=>p.moas))].sort().map(x=>({value:x,label:x}))])}<div class="nx-switch" role="group" aria-label="Mesure du podium"><button type="button" data-nxp-metric="projects" class="${s.metric==='projects'?'active':''}">Projets</button><button type="button" data-nxp-metric="housing" class="${s.metric==='housing'?'active':''}">Logements</button></div><button type="button" class="btn btn-secondary btn-small" data-nxp-reset="1">Réinitialiser</button></div>`;}
function controls(){const s=summary();return `<div class="control-section"><h3>Podium BBCA par DG Région</h3><p class="help">Même périmètre et mêmes filtres que la cartographie. Le switch <b>Projets / Logements</b> change la mesure utilisée pour classer les DG.</p><div class="nx-check-counts">${f(s.projects.length)} projets uniques<br>${f(s.projects.reduce((a,p)=>a+(Number(p.housing)||0),0))} logements<br>Mesure active : ${s.metric==='projects'?'nombre de projets':'nombre de logements'}</div><p class="help">Pour les logements, Obslide utilise la colonne <b>Total logements</b>. Lorsqu’un Code interne apparaît sur plusieurs lignes, la valeur maximale du projet est retenue afin d’éviter le double comptage.</p></div>`;}
function text(value,x,y,size,width=1000,opts={}){const raw=String(value??''),scale=bridge?.scale?.()||1;let fs=Math.min(size*scale,opts.maxSize||size*1.4);if(!measureCtx)measureCtx=document.createElement('canvas').getContext('2d');measureCtx.font=`${opts.weight||600} ${fs}px Arial`;if(width&&measureCtx.measureText(raw).width>width)fs*=width/measureCtx.measureText(raw).width;return `<text x="${x}" y="${y}" font-family="Arial,Helvetica,sans-serif" font-size="${fs.toFixed(2)}" font-weight="${opts.weight||600}" fill="${opts.color||'#06402b'}" text-anchor="${opts.anchor||'start'}" dominant-baseline="middle">${e(raw)}</text>`;}
const rect=(x,y,w,h,fill='#fff',stroke='#d5e1da',r=16)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${fill}" stroke="${stroke}"/>`;
function svg(m=model()){const s=summary(m),levels=[['BBCA Excellence','EXCELLENCE'],['BBCA Performance','PERFORMANCE'],['BBCA Standard','STANDARD']];let out=`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900"><rect width="1600" height="900" fill="#fff"/>`;out+=text(m.title,40,56,36,1260,{weight:800,maxSize:46})+text(`${m.subtitle} · classement par ${s.metric==='projects'?'nombre de projets':'nombre de logements'}`,42,98,18,1260,{weight:500,color:'#53695d'});if(bridge.logo)out+=`<image href="${bridge.logo}" x="1442" y="18" width="113" height="83" preserveAspectRatio="xMidYMid meet"/>`;levels.forEach(([level,label],col)=>{const x=42+col*510,w=486;out+=rect(x,145,w,660,'#f8fbf9','#d8e5dd',18)+text(label,x+24,177,22,w-48,{weight:800})+text(s.metric==='projects'?'nombre de projets certifiés':'nombre de logements concernés',x+24,207,12,w-48,{weight:600,color:'#6d7e74'});const top=s.rankings[level].slice(0,7);top.forEach((r,i)=>{const yy=235+i*78,val=r.byLevel[level][s.metric],pcount=r.byLevel[level].projects,hcount=r.byLevel[level].housing;out+=`<g><rect x="${x+18}" y="${yy}" width="${w-36}" height="64" rx="12" fill="${i<3?'#ffffff':'#fbfcfb'}" stroke="#e3ebe6"/><circle cx="${x+48}" cy="${yy+32}" r="19" fill="${i===0?'#f3d36b':i===1?'#d9dde0':i===2?'#d9a36d':'#e8efea'}"/>${text(String(i+1),x+48,yy+32,14,32,{anchor:'middle',weight:900,color:'#274635'})}${text(r.name,x+77,yy+23,12.2,w-185,{weight:800,maxSize:14})}${text(`${f(pcount)} projet${pcount>1?'s':''} · ${f(hcount)} logement${hcount>1?'s':''}`,x+77,yy+43,9.3,w-190,{weight:600,color:'#65766b'})}${text(f(val),x+w-30,yy+32,21,105,{anchor:'end',weight:900,maxSize:25})}</g>`;});});out+=text(`Classement DG Région · ${s.metric==='projects'?'projets uniques (Code interne)':'logements (Total logements par projet)'}`,42,846,11,1450,{weight:500,color:'#6b7d72'})+'</svg>';return out;}
async function png(){const blob=new Blob([svg()],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob);try{const img=new Image();await new Promise((r,j)=>{img.onload=r;img.onerror=j;img.src=url;});const c=document.createElement('canvas');c.width=3840;c.height=2160;c.getContext('2d').drawImage(img,0,0,c.width,c.height);return await new Promise((r,j)=>c.toBlob(b=>b?r(b):j(new Error('PNG podium impossible')),'image/png'));}finally{URL.revokeObjectURL(url);}}
function configure(b){bridge=b;}
document.addEventListener('change',ev=>{if(!bridge?.isActive())return;const t=ev.target;if(t.matches('[data-nxp-mention]')){const vals=[...document.querySelectorAll('[data-nxp-mention]:checked')].map(x=>x.value);model().filters={...(model().filters||{}),mentions:vals,mention:'all'};bridge.refresh(false);return;}if(t.matches('[data-nxp-filter]')){model().filters={...(model().filters||{}),[t.dataset.nxpFilter]:t.value};bridge.refresh(false);}});
document.addEventListener('click',ev=>{if(!bridge?.isActive())return;const ma=ev.target.closest('[data-nxp-mention-action]');if(ma){const all=[...document.querySelectorAll('[data-nxp-mention]')],vals=ma.dataset.nxpMentionAction==='all'?all.map(x=>x.value):[];model().filters={...(model().filters||{}),mentions:vals,mention:'all'};bridge.refresh(false);return;}const metric=ev.target.closest('[data-nxp-metric]');if(metric){model().metric=metric.dataset.nxpMetric==='housing'?'housing':'projects';bridge.refresh(false);return;}if(ev.target.closest('[data-nxp-reset]')){model().filters={...defaults.filters};model().metric='projects';bridge.refresh(false);}});
window.OBSNexityPodium={defaults,configure,controls,toolbar,svg,png,summary};})();
