/* Nexity data engine - department-driven DR mapping, one Code interne = one project. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.OBSNexityCore=api;})(globalThis,function(){
'use strict';
const clean=v=>String(v??'').normalize('NFC').replace(/\u00a0/g,' ').trim().replace(/\s+/g,' ');
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const FIELDS={
 direction:['DIRECTION REGIONALE','Direction regionale Nexity','directionRegionale','regionalDirection','DR Nexity','DR'],
 department:['Departement','Département','Code departement','Code département','Departement operation','Département opération','Département de l operation','department'],
 code:['Code interne','Evaluation: Operation: Code interne','Operation: Code interne','Code projet','Code operation','code'],
 name:["Nom de l'operation (interne)",'Nom operation',"Nom de l'operation",'Nom du programme (client)','Nom du programme','Programme','Operation','name'],
 moa:["Maitre d'ouvrage: Nom de la societe","Maître d'ouvrage: Nom de la société","Maitre d'ouvrage","Maître d'ouvrage",'MOA'],
 year:['Annee','Année','Annee operation','year','Date de creation','Date de création','Evaluation: Date de creation'],
 mention:['Mentions','Mention','mention','Certification: Mention','Référentiel: Mention','Referentiel: Mention'],
 housing:['Total logements','Total Logements','TOTAL LOGEMENTS','Nombre total de logements','Nb logements','Nombre de logements','Logements']
};
function resolve(headers){const h=headers.map(norm),m={};Object.entries(FIELDS).forEach(([k,a])=>{m[k]=-1;for(const s of a){const i=h.indexOf(norm(s));if(i>=0){m[k]=i;break;}}});return m;}
function detectHeader(matrix){let best={index:0,score:-1,mapping:{}};matrix.slice(0,100).forEach((r,index)=>{const mapping=resolve(r||[]);const score=(mapping.department>=0?24:0)+(mapping.code>=0?7:0)+(mapping.mention>=0?5:0)+(mapping.direction>=0?2:0)+Object.values(mapping).filter(v=>v>=0).length;if(score>best.score)best={index,score,mapping};});return best;}
function parseText(input){const text=String(input||'').replace(/^\uFEFF/,'').replace(/\r\n?/g,'\n');if(!text.trim())return[];const lines=text.split('\n').filter(x=>x.trim());if(lines[0]?.trim().startsWith('|')&&lines.some(x=>/^\s*\|?\s*:?-{3,}/.test(x)))return lines.filter(x=>!/^\s*\|?\s*:?-{3,}/.test(x)).map(x=>x.trim().replace(/^\||\|$/g,'').split('|').map(v=>v.trim()));const counts={'\t':0,';':0,',':0};let q=false,nl=0;for(let i=0;i<text.length&&nl<10;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){i++;continue;}q=!q;}if(!q&&c in counts)counts[c]++;if(!q&&c==='\n')nl++;}const sep=Object.keys(counts).sort((a,b)=>counts[b]-counts[a])[0];const rows=[];let row=[],f='';q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){f+='"';i++;}else q=!q;}else if(!q&&c===sep){row.push(f);f='';}else if(!q&&c==='\n'){row.push(f);rows.push(row);row=[];f='';}else f+=c;}if(q)throw new Error('Guillemets non fermes dans le tableau.');if(f||row.length){row.push(f);rows.push(row);}return rows;}
function fromMatrix(matrix,header,mapping){const rows=[];let ignored=0;for(let i=header+1;i<matrix.length;i++){const c=matrix[i]||[];const r={sourceLine:i+1};Object.keys(FIELDS).forEach(k=>r[k]=mapping[k]>=0?clean(c[mapping[k]]):'');if(!r.department&&!r.direction&&!r.code&&!r.name&&!r.mention){ignored++;continue;}if(norm(r.department)==='departement'&&(!r.code||norm(r.code)==='code interne')){ignored++;continue;}if(!r.code&&/^(total|totaux|total general|sous total)$/.test(norm(r.name)||norm(r.department))){ignored++;continue;}rows.push(r);}return{rows,ignored};}
function fromObjects(objs){const headers=[...new Set(objs.flatMap(o=>Object.keys(o||{})))];const mapping=resolve(headers);return{...fromMatrix([headers,...objs.map(o=>headers.map(h=>o[h]??''))],0,mapping),mapping,headers};}
function directionIndex(catalog){const m=new Map();catalog.forEach(d=>{m.set(norm(d.name),d.id);m.set(norm(d.id),d.id);m.set(norm(d.name.replace(/\s+\d[\d/]*$/,'')),d.id);});return m;}
function resolveDirection(v,catalog,overrides={}){const n=norm(v);if(!n)return'';if(Object.prototype.hasOwnProperty.call(overrides,n))return catalog.some(d=>d.id===overrides[n])?overrides[n]:'';const m=directionIndex(catalog);return m.get(n)||m.get(n.replace(/^(?:nexity\s+)?(?:direction regionale|dr)\s+/,''))||'';}
function departmentCode(v,geo){let x=clean(v).toUpperCase().replace(/\.0$/,'');if(!x)return'';if(/^\d$/.test(x))x='0'+x;if(/^\d{2}$/.test(x)||/^2[AB]$/.test(x))return x;let m=x.match(/(?:^|\D)(\d{2})(?:\D|$)/);if(m)return m[1];const n=norm(x);return geo?.departmentNames?.[n]||'';}
function parseNumber(v){const s=clean(v).replace(/\s/g,'').replace(/,/g,'.').replace(/[^0-9.\-]/g,'');const n=Number(s);return Number.isFinite(n)?n:0;}
function bbcaLevel(values){const n=norm((values||[]).join(' | '));if(/bbca.*excellence|excellence.*bbca/.test(n))return'BBCA Excellence';if(/bbca.*performance|performance.*bbca/.test(n))return'BBCA Performance';if(/bbca.*standard|standard.*bbca/.test(n))return'BBCA Standard';return'Autre / sans BBCA';}
function aggregate(rows,catalog,overrides={},geo={}){
 const grouped=new Map();rows.forEach((r,i)=>{const k=r.code?'code:'+clean(r.code).toLocaleUpperCase('fr'):'line:'+i;if(!grouped.has(k))grouped.set(k,{key:k,code:r.code||'',name:r.name||'',rows:[]});const p=grouped.get(k);p.rows.push(r);if(!p.name&&r.name)p.name=r.name;});
 const projects=[...grouped.values()].map(p=>{
  p.rawDirections=[...new Set(p.rows.map(r=>clean(r.direction)).filter(Boolean))];p.rawDepartments=[...new Set(p.rows.map(r=>clean(r.department)).filter(Boolean))];
  p.departmentCodes=[...new Set(p.rawDepartments.map(v=>departmentCode(v,geo)).filter(Boolean))];p.mentions=[...new Set(p.rows.map(r=>clean(r.mention)).filter(Boolean))];p.bbcaLevel=bbcaLevel(p.mentions);p.housing=Math.max(0,...p.rows.map(r=>parseNumber(r.housing)));
  const deptIds=[...new Set(p.departmentCodes.map(c=>geo?.departmentToDirection?.[c]).filter(Boolean))];const dirIds=[...new Set(p.rawDirections.map(s=>resolveDirection(s,catalog,overrides)).filter(Boolean))];
  p.issues=[];p.directionId='';p.reason='';
  if(p.departmentCodes.length>1){p.reason='department-conflict';p.issues.push('Plusieurs départements pour le même Code interne');}
  else if(p.departmentCodes.length===1){const c=p.departmentCodes[0],d=geo?.departmentToDirection?.[c]||'';if(d){p.directionId=d;if(dirIds.length===1&&dirIds[0]!==d)p.issues.push('La DIRECTION RÉGIONALE source diffère du rattachement par département');}else{p.reason='department-unmapped';p.issues.push('Département '+c+' absent du référentiel DR Nexity fourni');}}
  else if(p.rawDepartments.length){p.reason='department-unknown';p.issues.push('Département non reconnu : '+p.rawDepartments.join(' / '));}
  else if(dirIds.length===1){p.directionId=dirIds[0];p.reason='fallback-direction';p.issues.push('Département absent : rattachement de secours par DIRECTION RÉGIONALE');}
  else if(dirIds.length>1){p.reason='direction-conflict';p.issues.push('Plusieurs directions pour le même Code interne');}
  else{p.reason='missing';p.issues.push('Département absent');}
  p.directionName=catalog.find(d=>d.id===p.directionId)?.name||'À vérifier';if(!p.code)p.issues.push('Code interne absent : cette ligne est comptée séparément');if(!p.name)p.name='Projet sans nom (ligne '+(p.rows[0].sourceLine||'?')+')';p.years=[...new Set(p.rows.map(r=>clean(r.year).match(/\b(?:19|20)\d{2}\b/)?.[0]).filter(Boolean))];p.moas=[...new Set(p.rows.map(r=>clean(r.moa)).filter(Boolean))];p.lines=p.rows.map(r=>r.sourceLine);return p;
 });
 const unknown=[...new Set(rows.map(r=>clean(r.department)).filter(Boolean).filter(v=>!departmentCode(v,geo)))].sort((a,b)=>a.localeCompare(b,'fr'));
 return{projects,unknown,rowCount:rows.length,duplicates:rows.length-projects.length};
}
function filter(projects,f={}){return projects.filter(p=>{if(f.direction&&f.direction!=='all'&&(f.direction==='__unassigned__'?!!p.directionId:p.directionId!==f.direction))return false;if(f.year&&f.year!=='all'&&!p.years.includes(f.year))return false;if(f.moa&&f.moa!=='all'&&!p.moas.includes(f.moa))return false;const ms=Array.isArray(f.mentions)?f.mentions.filter(Boolean):[];if(ms.length&&!ms.some(x=>p.mentions.includes(x)))return false;if(!ms.length&&f.mention&&f.mention!=='all'&&!p.mentions.includes(f.mention))return false;if(f.bbca&&f.bbca!=='all'&&p.bbcaLevel!==f.bbca)return false;if(f.search&&!norm([p.code,p.name,...p.rawDepartments,...p.rawDirections,...p.moas,...p.mentions].join(' ')).includes(norm(f.search)))return false;return true;});}
function stats(projects,catalog){const byDirection={};catalog.forEach(d=>{const ps=projects.filter(p=>p.directionId===d.id);const levels={'BBCA Excellence':0,'BBCA Performance':0,'BBCA Standard':0,'Autre / sans BBCA':0};ps.forEach(p=>levels[p.bbcaLevel]=(levels[p.bbcaLevel]||0)+1);byDirection[d.id]={total:ps.length,levels};});return byDirection;}
function csv(projects){const cell=v=>{let s=String(v??'');if(/^\s*[=+@\-]/.test(s)||/^[\t\r]/.test(s))s="'"+s;return'"'+s.replace(/"/g,'""')+'"';};return'\uFEFF'+[['Code interne',"Nom de l'operation (interne)",'Département','DIRECTION RÉGIONALE calculée','DIRECTION RÉGIONALE source','Mention(s)','Niveau BBCA','Total logements',"Maître d'ouvrage",'Années','Lignes sources','Contrôles'],...projects.map(p=>[p.code,p.name,p.departmentCodes.join(' | ')||p.rawDepartments.join(' | '),p.directionName,p.rawDirections.join(' | '),p.mentions.join(' | '),p.bbcaLevel,p.housing,p.moas.join(' | '),p.years.join(', '),p.lines.join(', '),p.issues.join(' | ')])].map(r=>r.map(cell).join(';')).join('\r\n');}
return{clean,norm,FIELDS,resolve,detectHeader,parseText,fromMatrix,fromObjects,resolveDirection,departmentCode,parseNumber,bbcaLevel,aggregate,filter,stats,csv};
});
